[tool.poetry]
name = "sphinx-scylla-theme"
version = "0.1.0"
description = ""
authors = ["Nick Volynkin <nick.volynkin@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
sphinx = "1.8.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pyyaml = "^5.3"
livereload = "^2.6.1"
recommonmark = "^0.6.0"
sphinx-tabs = "^1.1.13"
sphinx-copybutton = "^0.2.8"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
