[tool.poetry]
name = "sphinx-scylladb-theme"
version = "1.0.6"
description = "A Sphinx Theme for ScyllaDB documentation projects"
authors = ["David Garc√≠a <hi@davidgarcia.dev>"]
exclude = [".github", "config", "docs", ".postcss.config.js", ".prettierrc.json", "deploy.sh", "src", "package.json", "package-lock.json"]
readme = "PYPI.rst"

[tool.poetry.dependencies]
python = "^3.7"
pyyaml = "^6.0"
sphinx-copybutton = "^0.4.0"
Sphinx = "^2.4.5"
sphinx-multiversion-scylla = "^0.2.4"
sphinx-notfound-page = "^0.8"
recommonmark = "0.7.1"
beautifulsoup4 = "^4.10.0"
sphinx-tabs = "^3.2.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
sphinx-autobuild = "^2021.3.14"
pre-commit = "^2.16.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
