[tool.poetry]
name = "sphinx-scylladb-theme"
version = "1.4.1"
description = "A Sphinx Theme for ScyllaDB documentation projects"
authors = ["David Garc√≠a <hi@davidgarcia.dev>"]
exclude = [".github", "config", "docs", "extensions", ".postcss.config.js", ".prettierrc.json", "deploy.sh", "src", "package.json", "package-lock.json"]
readme = "PYPI.rst"

[tool.poetry.dependencies]
python = "^3.7"
sphinx-collapse = "^0.1.1"
sphinx-copybutton = ">=0.4,<0.6"
sphinx-notfound-page = "^0.8"
beautifulsoup4 = "^4.10.0"
sphinx-tabs = "^3.2.0"
Sphinx = "^4.3.2"
pyyaml = "^6.0"
Sphinx-Substitution-Extensions = "^2022.2.16"

[tool.poetry.dev-dependencies]
pytest = "^7.2.1"
sphinx-autobuild = "^2021.3.14"
pre-commit = "^2.21.0"
recommonmark = "^0.7.1"
setuptools = "^67.5.1"
sphinx-multiversion-scylla = "^0.2.18"
sphinx-sitemap = "^2.5.0"
redirects_cli ="^0.1.3"
importlib-metadata = "^6.0.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
