[tool.poetry]
name = "sphinx-scylladb-theme"
version = "1.5.1"
description = "A Sphinx Theme for ScyllaDB documentation projects"
authors = ["David Garc√≠a <hi@davidgarcia.dev>"]
exclude = [".github", "config", "docs", "extensions", ".postcss.config.js", ".prettierrc.json", "deploy.sh", "src", "package.json", "package-lock.json"]
readme = "PYPI.rst"

[tool.poetry.dependencies]
python = "^3.9"
sphinx-collapse = "^0.1.1"
sphinx-copybutton = ">=0.4,<0.6"
beautifulsoup4 = "^4.10.0"
sphinx-tabs = "^3.2.0"
pyyaml = "^6.0"
Sphinx-Substitution-Extensions = "^2022.2.16"
sphinx-notfound-page = "^1.0.0"

[tool.poetry.dev-dependencies]
pytest = "^7.4.2"
sphinx-autobuild = "^2021.3.14"
pre-commit = "^2.21.0"
myst-parser = "^2.0.0"
setuptools = "^68.0.0"
sphinx-multiversion-scylla = "^0.2.20"
sphinx-sitemap = "^2.5.1"
redirects_cli ="^0.1.3"
importlib-metadata = "^6.7.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
