[tool.poetry]
name = "sphinx-scylladb-theme"
version = "1.7.2"
description = "A Sphinx Theme for ScyllaDB documentation projects"
authors = ["David Garc√≠a <hi@davidgarcia.dev>"]
exclude = [".github", "config", "docs", "extensions", ".postcss.config.js", ".prettierrc.json", "deploy.sh", "src", "package.json", "package-lock.json"]
readme = "PYPI.rst"

[tool.poetry.dependencies]
python = "^3.9"
sphinx-collapse = "^0.1.1"
sphinx-copybutton = "^0.5.2"
beautifulsoup4 = "^4.12.2"
sphinx-tabs = "^3.4.1"
pyyaml = "^6.0.1"
Sphinx-Substitution-Extensions = "^2022.2.16"
sphinx-notfound-page = "^1.0.0"
importlib-metadata = ">=6.8,<8.0"

[tool.poetry.dev-dependencies]
pytest = "^8.1.1"
sphinx-autobuild = "^2024.2.4"
pre-commit = "^3.7.0"
myst-parser = "^2.0.0"
setuptools = "^69.2.0"
sphinx-multiversion-scylla = "^0.3.1"
sphinx-sitemap = "^2.5.1"
redirects_cli ="^0.1.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
